openapi: 3.0.0
info:
  title: User and People API
  description: API for user authentication and managing people details.
  version: 1.0.0

paths:
  /users/login:
    post:
      summary: Auth user & get token
      description: Authenticates a user and returns a JWT token.
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        "200":
          description: Successful authentication
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  username:
                    type: string
                  token:
                    type: string
        "401":
          description: Invalid username or password
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "500":
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /users/signup:
    post:
      summary: Register a new user
      description: Registers a new user and returns a JWT token.
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        "201":
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  username:
                    type: string
                  token:
                    type: string
        "400":
          description: User already exists or invalid user data
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "500":
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /people/details:
    get:
      summary: Get people counts
      description: Retrieves counts of people categorized by gender and age.
      tags:
        - People
      security:
        - bearerAuth: []
      responses:
        "200":
          description: People details retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      male:
                        type: integer
                      female:
                        type: integer
                      boy:
                        type: integer
                      girl:
                        type: integer
        "500":
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /people/modify:
    patch:
      summary: Update people details
      description: Updates the details of people counts.
      tags:
        - People
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                male:
                  type: integer
                female:
                  type: integer
                girl:
                  type: integer
                boy:
                  type: integer
              required:
                - male
                - female
                - girl
                - boy
      responses:
        "200":
          description: Details updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "500":
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
